
name: lumina_exam
description: Sri Lanka's premier AI-powered examination platform.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.0
  supabase_flutter: ^2.6.0
  provider: ^6.1.1
  google_fonts: ^6.2.1
  url_launcher: ^6.2.5
  intl: ^0.19.0
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
